// Generated by LiveScript 1.4.0
(function(){
  var request, iso8601, cheerio, async, grok, stationsInOne, stationsInTwo, stationsInThree, stationsInLongmen, stationsInLanyu, radiations, out$ = typeof exports != 'undefined' && exports || this;
  request = require('request');
  iso8601 = require('iso8601');
  cheerio = require('cheerio');
  async = require('async');
  import$(global, require('prelude-ls'));
  grok = curry$(function(prefix, url, respond){
    return request({
      url: url
    }, function(_err, _res, page){
      var $, t, r;
      if (_err) {
        console.log("taipower error: " + JSON.stringify(_err));
      }
      $ = cheerio.load(page);
      t = iso8601.fromDate(new Date(Date.parse($(".time").first().text() + " +0800")));
      r = [];
      $("td.time").each(function(){
        return r.push({
          location: prefix + this.prev().text(),
          time: t,
          value: this.text()
        });
      });
      return respond(_err, r);
    });
  });
  stationsInOne = grok('核一廠', 'http://wapp4.taipower.com.tw/nsis/web/new_screen_page/001s/intime_graph_1.asp');
  stationsInTwo = grok('核二廠', 'http://wapp4.taipower.com.tw/nsis/web/new_screen_page/002s/intime_graph_2.asp');
  stationsInThree = grok('核三廠', 'http://wapp4.taipower.com.tw/nsis/web/new_screen_page/003s/intime_graph_3.asp');
  stationsInLongmen = grok('龍門廠', 'http://wapp4.taipower.com.tw/nsis/web/new_screen_page/004s/intime_graph_4.asp');
  stationsInLanyu = grok('蘭嶼廠', 'http://wapp4.taipower.com.tw/nsis/web/new_screen_page/005l/intime_graph_5.asp');
  radiations = function(respond){
    return async.parallel([stationsInOne, stationsInTwo, stationsInThree, stationsInLongmen, stationsInLanyu], function(_err, results){
      return respond(concat(results));
    });
  };
  out$.radiations = radiations;
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
